import type { CuratedMapping } from "../config/types.js";

/**
 * Generate SKILL.md content from a curated mapping.
 * If no mapping, generates a stub from introspected tool names.
 */
export function generateSkill(
  serverName: string,
  mapping: CuratedMapping | null,
  introspectedTools?: string[]
): string {
  if (mapping) {
    return generateFromMapping(serverName, mapping);
  }
  if (introspectedTools) {
    return generateStub(serverName, introspectedTools);
  }
  throw new Error(`Cannot generate skill for "${serverName}": no mapping and no introspection data`);
}

function generateFromMapping(name: string, m: CuratedMapping): string {
  const toolRows = Object.entries(m.tools)
    .map(([mcpTool, t]) => {
      const args = t.args.length > 0 ? `<${t.args.join("> <")}>` : "";
      const cmd = args ? `${name}.sh ${t.subcommand} ${args}` : `${name}.sh ${t.subcommand}`;
      const notes = [t.output_format, t.guidance].filter(Boolean).join(". ");
      return `| ${mcpTool} | \`${cmd}\` | ${notes} |`;
    })
    .join("\n");

  const envRows = m.env_vars
    .map((v) => `- \`${v.name}\` ${v.required ? "(required)" : "(optional)"}: ${v.description}`)
    .join("\n");

  const installLines = Object.entries(m.cli.install)
    .map(([os, cmd]) => `  - ${os}: \`${cmd}\``)
    .join("\n");

  return `---
name: ${name}
description: Replaces MCP server with CLI commands. Generated by forget-mcp.
type: mcp-replacement
source_server: ${m.server_patterns[0]}
generated_by: forget-mcp v0.1.0
generated_at: ${new Date().toISOString()}
---

## Prerequisites

- CLI required: **${m.cli.name}** (check: \`${m.cli.version_check}\`)
${installLines}
- Environment variables:
${envRows}

## Operation Mapping

| MCP Tool | CLI Command | Notes |
|----------|-------------|-------|
${toolRows}

## Output Handling

- Use the \`tools/${name}.sh\` wrapper for truncated output (default: 200 lines)
- Override: \`FORGET_MCP_MAX_LINES=0 tools/${name}.sh <cmd>\` for full output
- For AI parsing: most commands output CSV or structured text

## Error Patterns

| Error | Cause | Fix |
|-------|-------|-----|
| command not found: ${m.cli.name} | CLI not installed | Run install command above |
| connection refused | Service not running | Check service status / connection string |
| permission denied | Auth issue | Check credentials in env vars |

${m.notes ? `## Notes\n\n${m.notes}\n` : ""}`;
}

function generateStub(name: string, tools: string[]): string {
  const toolRows = tools
    .map((t) => `| ${t} | \`# needs manual mapping\` | stub |`)
    .join("\n");

  return `---
name: ${name}
description: Stub skill generated from MCP introspection. Needs manual mapping.
type: mcp-replacement
status: incomplete
generated_by: forget-mcp v0.1.0
generated_at: ${new Date().toISOString()}
---

## Prerequisites

- CLI required: **unknown** (this is a stub, needs manual configuration)

## Operation Mapping

| MCP Tool | CLI Command | Notes |
|----------|-------------|-------|
${toolRows}

## Status

This skill was generated from MCP introspection but has no curated mapping.
Each tool above needs a manual CLI command mapping before it can be used.

To contribute a mapping: https://github.com/HeliosLz/forget-mcp/issues
`;
}
