import type { CuratedMapping } from "../config/types.js";

/**
 * Generate a bash wrapper script from a curated mapping.
 * The wrapper_template field contains the hand-written case body.
 * This function wraps it in the standard header (shebang, pipefail, MAX_LINES, help, error).
 */
export function generateWrapper(name: string, mapping: CuratedMapping): string {
  const subcommands = Object.values(mapping.tools)
    .map((t) => {
      const args = t.args.length > 0 ? ` <${t.args.join("> <")}>` : "";
      return `${t.subcommand}${args}`;
    })
    .join(", ");

  return `#!/usr/bin/env bash
# tools/${name}.sh — generated by forget-mcp
# Replaces: ${mapping.server_patterns[0]}
# CLI: ${mapping.cli.name} (${mapping.cli.version_check})
set -euo pipefail
MAX_LINES="\${FORGET_MCP_MAX_LINES:-200}"

${mapping.wrapper_template}

  help|"")
    echo "${name}.sh — replaces ${mapping.server_patterns[0]}"
    echo "Commands: ${subcommands}"
    ;;
  *)
    echo "Unknown command: \${1:-}. Run '${name}.sh help' for usage." >&2
    exit 1
    ;;
esac
`;
}
